// File generated by Gemini Code Assist.
//
// This file was generated from the `google-services.json` and other configuration
// files for the Firebase project `tiffin-tales-app`.
//
// To properly configure Firebase for all platforms, it's recommended to use
// the FlutterFire CLI: `flutterfire configure`
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class is designed to be used with `Firebase.initializeApp()`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'You can run `flutterfire configure` to generate them.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Values from c:\Users\uniqu\Downloads\account.html
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-If6ywbPaFhO7G0TVH_LTn-Q7f_Sw4PI',
    appId: '1:603754512478:web:c775c80929195f3ce2f4cf',
    messagingSenderId: '603754512478',
    projectId: 'tiffin-tales-app',
    authDomain: 'tiffin-tales-app.firebaseapp.com',
    storageBucket: 'tiffin-tales-app.firebasestorage.app',
    measurementId: 'G-WXFF4DPJ2H',
  );

  // Values from c:\Users\uniqu\Downloads\google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xRVLbVdvkz1UPKdsC0peHXMPpKz2Iy4',
    appId: '1:603754512478:android:f866a04b3948e020e2f4cf',
    //1:603754512478:android:3de623978d19f049e2f4cf-new
    //1:603754512478:android:f866a04b3948e020e2f4cf-old
    messagingSenderId: '603754512478',
    projectId: 'tiffin-tales-app',
    storageBucket: 'tiffin-tales-app.firebasestorage.app',
  );

  // iOS values are derived from the same Firebase project.
  // You should generate a GoogleService-Info.plist from the Firebase console
  // and run `flutterfire configure` to get the correct values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xRVLbVdvkz1UPKdsC0peHXMPpKz2Iy4',
    appId: '1:603754512478:ios:ddd4c25ad3e6843de2f4cf',
    messagingSenderId: '603754512478',
    projectId: 'tiffin-tales-app',
    storageBucket: 'tiffin-tales-app.firebasestorage.app',
    iosBundleId: 'com.example.tiffinTalesApp',
  );
}
